//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HGenealogy.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class City
    {
        public int Id { get; set; }
        public int LanguageID { get; set; }
        public int CountryId { get; set; }
        public string StateProviceName { get; set; }
        public string CityName { get; set; }
        public string ZipCode { get; set; }
        public bool Published { get; set; }
        public int DisplayOrder { get; set; }
    }
}
