//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HGenealogy.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Family
    {
        public int Id { get; set; }
        public string FNo { get; set; }
        public string FName { get; set; }
        public string GId { get; set; }
        public string FatherId { get; set; }
        public string MotherId { get; set; }
        public string BirthYear { get; set; }
        public Nullable<System.DateTime> BirthDay { get; set; }
        public string Address { get; set; }
        public Nullable<decimal> AddressLongitude { get; set; }
        public Nullable<decimal> AddressLatitude { get; set; }
        public string Phone1 { get; set; }
        public string Phone2 { get; set; }
        public string Email { get; set; }
        public string FatherName { get; set; }
        public string MoterName { get; set; }
        public string GFatherName { get; set; }
        public string GGFatherName { get; set; }
        public string Gender { get; set; }
        public string Mate { get; set; }
        public Nullable<int> GenerationNo { get; set; }
        public string Job { get; set; }
        public string Notes { get; set; }
        public string Childrens { get; set; }
        public string LungName { get; set; }
        public string HakkaName { get; set; }
    }
}
