//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HGenealogy.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class GenealogyMeta
    {
        public string GID { get; set; }
        public string GName { get; set; }
        public bool IsPublic { get; set; }
        public string Editor { get; set; }
        public string PublishDate { get; set; }
        public string Volumes { get; set; }
        public Nullable<int> Pages { get; set; }
        public string Interviewer { get; set; }
        public string FamilyName { get; set; }
        public string OriginalAncestor { get; set; }
        public string DateMoveToTaiwan { get; set; }
        public string AncestorToTaiwan { get; set; }
        public string OriginalAddress { get; set; }
        public Nullable<int> Generations { get; set; }
        public string GenerationToTaiwan { get; set; }
        public string LivingAreaInTaiwan { get; set; }
        public string Collector { get; set; }
        public string ContentNotes { get; set; }
        public string ZhaoMu { get; set; }
        public string TangName { get; set; }
    }
}
