//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HGenealogy.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class PedigreeMeta
    {
        public int Id { get; set; }
        public string Title { get; set; }
        public string Editor { get; set; }
        public string Description { get; set; }
        public byte[] Image { get; set; }
        public Nullable<System.DateTime> PublishDate { get; set; }
        public int Volumes { get; set; }
        public int Pages { get; set; }
        public string FamilyName { get; set; }
        public string OriginalAncestor { get; set; }
        public string DateMoveToTaiwan { get; set; }
        public string AncestorToTaiwan { get; set; }
        public string OriginalAddress { get; set; }
        public int TotalGenerations { get; set; }
        public int GenerationToTaiwan { get; set; }
        public string LivingAreaInTaiwan { get; set; }
        public string OriginalCollector { get; set; }
        public string ContentNotes { get; set; }
        public string TangName { get; set; }
        public bool IsPublic { get; set; }
        public bool IsPublished { get; set; }
        public bool IsDeleted { get; set; }
        public System.DateTime CreatedOnUtc { get; set; }
        public System.DateTime UpdatedOnUtc { get; set; }
        public string CreatedWho { get; set; }
        public string UpdatedWho { get; set; }
        public byte[] LastChanged { get; set; }
    }
}
